More flexible TOOL_VERSIONS_MANAGER setup

diff --git a/bin/env/ruby-setup b/bin/env/ruby-setup
--- a/bin/env/ruby-setup
+++ b/bin/env/ruby-setup
@@ -2,15 +2,26 @@
 set -euo pipefail
 PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd ../.. > /dev/null 2>&1 && pwd -P)"
 
-if command -v mise &> /dev/null; then
-    mise install ruby
-else # setup ruby via asdf  
+source $PROJECT_DIR/bin/env/select-tool-versions-manager.bash
+
+case "$TOOL_VERSIONS_MANAGER" in
+  asdf|asdf-vm)
+    echo "Setting up ruby via asdf"
     ASDF_PLUGIN=ruby
     ASDF_PLUGIN_URL=https://github.com/asdf-vm/asdf-ruby.git
     source $PROJECT_DIR/bin/env/asdf-helper.bash
     asdf-update-plugin
     asdf install ruby
-fi 
+    ;;
+  mise)
+    echo "Setting up ruby via mise"
+    mise install ruby
+    ;;
+  *)
+    echo "ERROR: Unsupported TOOL_VERSIONS_MANAGER: $TOOL_VERSIONS_MANAGER"
+    exit 1
+    ;;
+esac
 
 bundle install --quiet
 # vi: ft=sh
